portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  get  '/about',    to: 'static_pages#about'
  get  '/help',     to: 'static_pages#help'
  

  resources :microposts,          only: [:create, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :fileas,              only: [:new, :create, :destroy]

  resources :users  do
    collection do
      get 'set'
      get 'search'
    end
    member do
      get 'following'
      get 'followers'
      get 'show2'
      get 'show3'
    end
  end

  resources :notices do
    collection do
      get 'search'
    end
  end
  
  resources :messages,           only: [:create]
  resources :rooms,              only: [:create, :show, :index]
  resources :relationships,       only: [:create, :destroy]
end

portfolio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

portfolio/app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

portfolio/app/models/filea.rb
class Filea < ApplicationRecord
		mount_uploader :file, FileUploader
		belongs_to :user
end

portfolio/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

portfolio/app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140}
end

portfolio/app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :notice_title, presence: true, length: {maximum: 50}
  validates :notice_body,  presence: true, length: { maximum: 255}
  #掲示板のプルダウンメニュー
  enum area:{
    オンライン:0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
    沖縄県:47
  }
end

portfolio/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

portfolio/app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

portfolio/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
				 :confirmable, :omniauthable, omniauth_providers:[:twitter,:facebook]
	mount_uploader :image, ImageUploader
	has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
																	dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
																	foreign_key: "followed_id",
																	dependent:   :destroy																													
	has_many :following, through: :active_relationships, source: :followed	
	has_many :followers, through: :passive_relationships, source: :follower															
	has_many :microposts, dependent: :destroy
	has_many :notices, dependent: :destroy
	has_many :messages, dependent: :destroy
	has_many :fileas,	dependent: :destroy
  has_many :entries, dependent: :destroy
	validates :introduction, length: {maximum: 160}
	#プロフィールのプルダウンメニュー
  enum area:{
    未登録:0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
    沖縄県:47
  }
		

	  # ユーザーをフォローする
		def follow(other_user)
			following << other_user
		end
	
		# ユーザーをフォロー解除する
		def unfollow(other_user)
			active_relationships.find_by(followed_id: other_user.id).destroy
		end
	
		# 現在のユーザーがフォローしてたらtrueを返す
		def following?(other_user)
			following.include?(other_user)
		end


end

portfolio/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    #自分のエントリーを取得
    user_entries = current_user.entries
    #エントリーから所持するroom_idを取得
    user_rid = user_entries.map do |entry|
      entry.room_id
    end
    #room_idから所属するRoom情報を取得
    current_user_rooms =  user_rid.map do |id|
      Room.where(id: id)
    end

    #Room情報から共通するRoom_idを持つユーザー情報の取得
    users_array = current_user_rooms.map do |room|
      users = Entry.where(room_id: room.ids).where.not(user_id: current_user.id)
      users.map do |user|
        User.find_by(id: user.user_id)
      end
    end
    #配列が二重になったので苦肉の策
    @users = users_array.flatten
  
    #自分のEntry情報を取得
    @currentUserEntry=Entry.where(user_id: current_user.id)

  end
end

portfolio/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]


  def show
    profile_show
    @notices = @user.notices.paginate(page: params[:page])
  end

  def show2
    profile_show
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def show3
    profile_show
    @files = @user.fileas
  end


  def index
    @indeies = User.all
  end
  

  def edit
    @user = User.find_by(id: current_user)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールを編集しました"
      redirect_to @user
    else
      render 'edit'
    end
    
  end

  
  def search
    if params[:area]
      @users = User.where(area: params[:area])
    elsif params[:search]
      if !params[:search].blank?
        @users = User.where("name LIKE ? OR introduction LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
      end
    else
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  

  def message
    @message = current_user.entries
  end
  

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :file, :area, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user == @user
  end
  
end

portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

portfolio/app/helpers/fileas_helper.rb
module FileasHelper
end

portfolio/app/helpers/messages_helper.rb
module MessagesHelper
end

portfolio/app/helpers/microposts_helper.rb
module MicropostsHelper
end

portfolio/app/helpers/notices_helper.rb
module NoticesHelper
end

portfolio/app/helpers/rooms_helper.rb
module RoomsHelper

  def room
    if @user.id == current_user.id
    else
        @currentUserEntry.each do |cu|
            @userEntry.each do |u|
                if cu.room_id == u.room_id then
                    @isRoom = true
                    @roomId = cu.room_id
                end
            end
        end
        if @isRoom
        else
            @room = Room.new
            @entry = Entry.new
        end
    end
  end

  def profile_show
    @user = User.find_by(id: params[:id])
    #プロフィール画面で掲示板投稿を表示
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    room
  end
end

portfolio/app/helpers/sessions_helper.rb
module SessionsHelper


    
    
    
end

portfolio/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

portfolio/app/helpers/users_helper.rb
module UsersHelper
end

portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SA | Home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag   'application', media: 'all',
                              'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag   'application',
                              'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
  </head>
  <body>
  <div class="wrap">
      <% if user_signed_in? %>
      <div class="menu">
        <div class="menu_inner">
          <div class="hrader_logo">
            <h1 class="logo logo">
              <%= image_tag 'site_logo.png', class: "logo_image logo_iamage2" %>
            </h1>
          </div>
          <ul class="menu_list" >
            <li class="menu_list_li"> <%= link_to "ホーム", root_path, class:"menu_list_item" %></li>
            <li class="menu_list_li"> <%= link_to "検索", search_notices_path, class:"menu_list_item" %></li>
            <li class="menu_list_li"> <%= link_to "掲示板", notices_path, class:"menu_list_item" %></li>
            <li class="menu_list_li"> <%= link_to "メッセージ", rooms_path, class:"menu_list_item" %></li>
            <li class="menu_list_li"> <%= link_to "プロフィール", "/users/#{current_user.id}", class:"menu_list_item" %></li>
            <li class="menu_list_li"> <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトします？"}, class:"menu_list_item" %></li>
            <li class="menu_list_li"> <%= link_to "設定", edit_user_registration_path, class:"menu_list_item" %></li>
          </ul> 
        </div>
      </div>
      <% else %>
        <div class="header active">
          <div class="header_logo">
            <h1 class="logo">
              <a class="logo_link">
                <%= link_to "SCIENCE ALLIANCE", root_path, class: "logo_image"%>
              </a>
            </h1>
          </div>
          <nav class="global-nav">
            <ul class="global-nav_list">
              <li class="global-nav_item">
                <a>
                  <%= link_to "home", root_path, class: "global-nav_link" %>
                </a>
              </li>
              <li class="global-nav_item">
                <a>
                  <%= link_to "about", about_path, class:"global-nav_link" %>
                </a>
              </li>
              <li class="global-nav_item">
                <a>
                  <%= link_to "help", help_path, class:"global-nav_link"%>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      <% end %>
    <%if user_signed_in? %>  
      <div class="main_container">
        <% flash.each do |message_type, message|%>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}")%>
        <% end %>
        <%= yield %>
      </div>
    <% else %>
      <div class="hero" style="height:	837px;">
          <% flash.each do |message_type, message|%>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}")%>
          <% end %>
        <%= yield %>
      </div>
    <% end %>
  </div>
  </body>
</html>

portfolio/app/views/shared/_error_messages.html.erb
<% if object.errors.any?  %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<%  end %>

portfolio/app/views/shared/_error_messages2.html.erb
<% if object.errors.any?  %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<%  end %>

portfolio/app/views/shared/_micropost_form.html.erb
<div class="notice_container">
      <% if @microposts %>
        <%  @microposts.each do |micropost| %>
          <div class="notice_container_item">
            <div class="notice_container_item2">
            <%= link_to "/users/#{micropost.user.id}" do %>
              <div class="notice_container_item_image">
                <div class="user_image">
                  <% if micropost.user.image? %>                                                              
                    <%= image_tag micropost.user.image.url(:thumb100), class: "image" %>
                  <%  else %>
                    <img src="/assets/default.png" class="image" alt="ユーザーアイコン" >
                  <% end %>
                </div>
              </div>
                <%end%>
              <div class="microposts_contents">
                <div class="microposts_info">
                  <div class="microposts_info_user">
                    <div class="micropost_user">
                      <%= micropost.user.name%>
                    </div>
                    <div class="micropost_time">
                        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
                    </div>
                  </div>
                  <div class="microposts_delete">
                    <%if current_user == micropost.user %>
                      <%= link_to "削除", micropost_path(micropost.id), method: :delete,
                                    data: { confirm: "You sure?"}%>
                    <% end %>
                  </div>
                </div>
                <div class="micropost_content">
                  <%= safe_join(micropost.content.split("\n"),tag(:br)) %>
                </div>
              </div>
          </div>
          </div>
        <% end %>
        <div class="pagenate_tag">
          <%= will_paginate @microposts%>
        </div>
        <% end %>
    </div>
  </div>

portfolio/app/views/shared/_notice_form.html.erb
 <div class="notice_container">
    <% if @notices %>
      <% @notices.each do |notice| %>
        <div class="notice_container_item post_back">
          <%=  link_to notice_path(notice), class: "notice_container_item2" do %>
            <div class="notice_container_item_image">
              <div class="user_image">
                  <% if notice.user.image? %>                                                              
                    <%= image_tag notice.user.image.url(:thumb100), class: "image"%>
                  <% else %>
                    <img src="/assets/default.png" class="image" alt="ユーザーアイコン" >
                  <% end %>
              </div>
            </div>
            <div class="microposts_contents"> 
              <div class="microposts_info">
                <div class="microposts_info_user">
                  <div class="micropost_user">
                    投稿者: <%= notice.user.name%>
                  </div>
                  <div class="micropost_area">
                    地域: <%= notice.area %>
                  </div> 
                  <div class="micropost_time">
                    Posted <%= time_ago_in_words(notice.created_at) %> ago.
                  </div>
                </div>
              </div>
              <div class="notice_title">
                <%= notice.notice_title %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="pagenate_tag">
        <%= will_paginate @notices%>
      </div>
    <% end %>
  </div>

portfolio/app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

portfolio/app/views/shared/_user_image2.html.erb
<div class="profile_image_area">
  <div class="user_image2">
    <% if @user.image? %>                                                              
      <%= image_tag @user.image.url(:thumb), class: "image2" %>
    <% else %>
      <img src="/assets/default.png" class="image2" alt="ユーザーアイコン" >
    <% end %>
  </div>
</div>