portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'
  get  '/about',    to: 'static_pages#about'
  get  '/help',     to: 'static_pages#help'
  

  resources :microposts,          only: [:create, :destroy] do
    collection do
      get 'search'
    end
  end

  resources :fileas,              only: [:new, :create, :destroy]

  resources :users  do
    collection do
      get 'set'
      get 'search'
    end
    member do
      get 'following'
      get 'followers'
      get 'show2'
      get 'show3'
    end
  end

  resources :notices do
    collection do
      get 'search'
    end
  end
  
  resources :messages,           only: [:create]
  resources :rooms,              only: [:create, :show, :index]
  resources :relationships,       only: [:create, :destroy]
end

portfolio/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
				 :confirmable, :omniauthable, omniauth_providers:[:twitter,:facebook]
	mount_uploader :image, ImageUploader
	has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
																	dependent:   :destroy
	has_many :passive_relationships, class_name:  "Relationship",
																	foreign_key: "followed_id",
																	dependent:   :destroy																													
	has_many :following, through: :active_relationships, source: :followed	
	has_many :followers, through: :passive_relationships, source: :follower															
	has_many :microposts, dependent: :destroy
	has_many :notices, dependent: :destroy
	has_many :messages, dependent: :destroy
	has_many :fileas,	dependent: :destroy
  has_many :entries, dependent: :destroy
	validates :introduction, length: {maximum: 160}
	#プロフィールのプルダウンメニュー
  enum area:{
    未登録:0,
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
    沖縄県:47
  }
		

	  # ユーザーをフォローする
		def follow(other_user)
			following << other_user
		end
	
		# ユーザーをフォロー解除する
		def unfollow(other_user)
			active_relationships.find_by(followed_id: other_user.id).destroy
		end
	
		# 現在のユーザーがフォローしてたらtrueを返す
		def following?(other_user)
			following.include?(other_user)
		end


end

portfolio/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

portfolio/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

portfolio/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

portfolio/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

portfolio/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

portfolio/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

portfolio/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]


  def show
    profile_show
    @notices = @user.notices.paginate(page: params[:page])
  end

  def show2
    profile_show
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def show3
    profile_show
    @files = @user.fileas
  end


  def index
    @indeies = User.all
  end
  

  def edit
    @user = User.find_by(id: current_user)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィールを編集しました"
      redirect_to @user
    else
      render 'edit'
    end
    
  end

  
  def search
    if params[:area]
      @users = User.where(area: params[:area])
    elsif params[:search]
      if !params[:search].blank?
        @users = User.where("name LIKE ? OR introduction LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
      end
    else
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  

  def message
    @message = current_user.entries
  end
  

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :file, :area, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user == @user
  end
  
end

portfolio/app/helpers/users_helper.rb
module UsersHelper
end

portfolio/app/views/users/_files_profile.html.erb
<div class="media_wrapper">
  <%if @files.blank?%>
  <%else%>
    <div class="media_items">
      <% @files.each do |file| %>
        <div class="media_item">
          <div class="media_item_title">
            <%= file.title %>
          </div>
          <object data="<%= file.file.url %>" type="application/pdf" width="200" height="300"></object>
          <% if @user == current_user %>
            <div>
              <%= link_to("削除", filea_path(file.id),  method: :delete,
                                    data: { confirm: "You sure?"}, class: "link_item_position")%> 
            </div>
          <%end%>
        </div>
      <%end%>
    </div>
  <%end%>
</div>

portfolio/app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

portfolio/app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

portfolio/app/views/users/_link_profile.html.erb
<% if @user == current_user %>
  <div class="plofile_editer">
    <div><%= link_to "編集", edit_user_path(@user.id)  %></div>
    <div><%= link_to "pdfをアップロード", new_filea_path %></div>
  </div>
<% end %>
<div class="profile_link_wrapper">

  <div class="profile_link_item">
    <%= link_to "掲示板", "/users/#{@user.id}",{class: "link_item_position"}%>
  </div>

  <div class="profile_link_item">
    <%= link_to "マイクロポスト", "/users/#{@user.id}/show2",{class: "link_item_position"}%>
  </div>

  <div class="profile_link_item">
    <%= link_to "メディア", "/users/#{@user.id}/show3",{class: "link_item_position"}%>
  </div>

</div>  

portfolio/app/views/users/_microposts_profile.html.erb
    <div class="notice_container">
      <% if @microposts %>
        <%  @microposts.each do |micropost| %>
          <div class="notice_container_item">
            <div class="notice_container_item2">
              <div class="notice_container_item_image">
                <div class="user_image">
                <% if micropost.user.image? %>                                                              
                  <%= image_tag micropost.user.image.url(:thumb100), class: "image"%>
                <% else %>
                  <img src="/assets/default.png" class="image" alt="ユーザーアイコン" >
                <% end %>
                </div>
              </div>
              <div class="microposts_contents">
                <div class="microposts_info">
                  <div class="microposts_info_user">
                    <div class="micropost_user">
                       <%= micropost.user.name%>
                    </div>
                    <div class="micropost_time">
                        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
                    </div>
                  </div>
                  <div class="microposts_delete">
                    <%if current_user?(micropost.user)%>
                      <%= link_to "削除", micropost_path(micropost.id),method: :delete,
                                    data: { confirm: "You sure?"}%>
                    <% end %>
                  </div>
                </div>
                <div class="micropost_content">
                  <%= safe_join(micropost.content.split("\n"),tag(:br)) %>
                </div>
              </div>
          </div>
          </div>
        <% end %>
        <% end %>
    </div>

portfolio/app/views/users/_notice_profile.html.erb
    <div class="notice_container">
    <% if @notices %>
    <%  @notices.each do |notice| %>
      <div class="notice_container_item post_back">
        <%=  link_to notice_path(notice), class: "notice_container_item2" do %>
        <div class="notice_container_item_image">
          <div class="user_image">
            <% if notice.user.image? %>                                                              
                <%= image_tag notice.user.image.url(:thumb100), class: "image"%>
            <% else %>
                <img src="/assets/default.png" class="image" alt="ユーザーアイコン" >
            <% end %>
          </div>
        </div>
        <div class="microposts_contents"> 
          <div class="microposts_info">
          <div class="microposts_info_user">
            <div class="micropost_user">
              投稿者: <%= notice.user.name%>
            </div>
            <div class="micropost_area">
              地域: <%= notice.area %>
            </div> 
            <div class="micropost_time">
              Posted <%= time_ago_in_words(notice.created_at) %> ago.
            </div>
          </div>
          </div>
          <div class="notice_title">
            <%= notice.notice_title %>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
    <% end %>
  </div>

portfolio/app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
            html: { method: :delete }, local: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

portfolio/app/views/users/_userinfo_profile.html.erb
<div class="profile_wrapper">
              <div class="profile_info_b">
                <div class="profile_info_c">
                  <div class="profile_user_info">
                    <div class="user_name">
                      <%= @user.name%>
                    </div>
                    <p>登録地域　<%= @user.area%></p>
                  </div>
                  <div class="profile_icons">
                    <%= render 'follow_form' if user_signed_in? %>
                    <% if @user.id == current_user.id %>
                    <% else %>
                      <% if @isRoom == true %>
                        <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
                      <% else %>
                        <%= form_for @room do |f| %>
                          <%= fields_for @entry do |e| %>
                            <%= e.hidden_field :user_id, :value=> @user.id %>
                          <% end %>
                          <%= f.submit "チャットを始める", class: "btn btn-primary" %>
                        <% end %>
                      <% end %>
                    <%end%>
                  </div>
                </div>
                <section class="stats">
                  <%= render 'shared/stats' %>
                </section>
              </div>
          </div>
          <div class="introduction_wrapper">
            <% if @user.introduction? %>
              <%= safe_join(@user.introduction.split("\n"),tag(:br)) %>
            <% end %>
          </div>

portfolio/app/views/users/edit.html.erb
<div class="microposts">
	<div class="title_container">
		<h1 class="content">プロフィール編集</h1>
	</div>

	<div class="u_edit_s">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
			<div class="u_set_container">
			<%= form_with model: @user do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
				<div>
				<%= f.label :image %>
				<%= f.file_field :image , class: "form-control	u_set_li"%>
				</div>

				<div>
				<%= f.label :name %>
				<%= f.text_field :name , class: "form-control u_set_li"%>
				</div>

				<div>
				<%= f.label	:自己紹介%>
				<%= f.text_area :introduction, class: "form u_set_li aasa" %>
				</div>

				<div>
				<%= f.label :area %>
				<%= f.select :area, User.areas.keys, {}, {class: 'hoge u_set_li'} %>
				</div>

				<%= f.submit"登録",	class: "btn btn-primary" %>
			<% end %>
			</div>
			</div>
		</div>

	</div>
</div>

portfolio/app/views/users/search.html.erb
<div class="microposts">
  <div class="title_container"> 
    <h1 class="content">ユーザー検索</h1>
  </div> 

  <div class="notice_creater_container">
    <div class="notice_creater">
      検索項目
      <%= link_to "掲示板", search_notices_path %>
      <%= link_to "ユーザー", search_users_path %>
      <%= link_to "マイクロポスト", search_microposts_path %>
      <%= form_with url:'/users/search', method: :get do |f| %>
      
      <%= f.label :登録地域 %>
      <%= f.select :area, User.areas.keys, {}, {class: 'hoge'} %>

      <%= f.submit"検索", class: "btn btn-primary" %>
      <% end %>

      <%= form_tag(search_users_path, :method => "get") do %>
      <%= text_field_tag :search %>
      <%= submit_tag"キーワード検索", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

  <div class="notice_container">
      <% if @users  %>
        <%  @users.each do |user| %>
          <%=  link_to "/users/#{user.id}" do %>
          <div class="notice_container_item">
            <div class="notice_container_item2">
              <div class="notice_container_item_image">
                <div class="user_image">
                  <% if user.image? %>                                                              
                    <%= image_tag user.image.url(:thumb100), class: "image" %>
                  <% else %>
                    <img src="/assets/default.png" class="image" alt="ユーザーアイコン" >
                  <% end %>
                </div>
              </div>
              <div class="microposts_contents">
                <div class="microposts_info">
                  <div class="microposts_info_user">
                    <div class="micropost_user">
                      <%= user.name%>
                    </div>
                  </div>
                </div>
                <div class="micropost_content">
                  <%= user.introduction %>
                </div>
              </div>
          </div>
          </div>
        <% end %>
        <% end %>
      <% end %>
    </div>
</div>

portfolio/app/views/users/show.html.erb
<div class="microposts">
    <div class="title_container">
      <h1 class="content">プロフィール</h1>
    </div>
  <div class="profile_main">
      <div class="profile_main2">
          <div class="profile_info">
            <div class="profile_info_a">
          <%= render "shared/user_image2" %>  
          <%= render "userinfo_profile" %>
      <%= render "link_profile" %>
      <%= render "notice_profile" %>
     </div>
    </div>
  </div>
</div>
</div>

portfolio/app/views/users/show2.html.erb
<div class="microposts">
    <div class="title_container">
      <h1 class="content">プロフィール</h1>
    </div>
  <div class="profile_main">
      <div class="profile_main2">
          <div class="profile_info">
            <div class="profile_info_a">
          <%= render "shared/user_image2" %>      
          <%= render "userinfo_profile" %>
    <%= render "link_profile" %>
    <%= render "shared/micropost_form"  %>
        </div>
        </div>
  </div>
</div>
</div>

portfolio/app/views/users/show3.html.erb
<div class="microposts">
    <div class="title_container">
      <h1 class="content">プロフィール</h1>
    </div>
  <div class="profile_main">
      <div class="profile_main2">
          <div class="profile_info">
            <div class="profile_info_a">
          <%= render "shared/user_image2" %>
          <%= render "userinfo_profile" %>
          
      <%= render "link_profile" %>
      <%= render "files_profile"%>  
        </div>
        </div>
  </div>
</div>
</div>

portfolio/app/views/users/show_follow.html.erb
<div class="microposts">
  <div class="title_container ccc">
    <h1 class="content"><%=@user.name%></h1>
    <%= link_to "プロフィールに戻る", @user, {class:"back_profile"} %>
  </div>

  <div class="follow_container">
    <div class="follow_links">
      <div class="following_link follow_set">
        <%= link_to "フォロー中", following_user_path(@user), {class: "follow_link_set"} %>
      </div>
      <div class="followers_link follow_set">
        <%= link_to "フォロワー", followers_user_path(@user), {class: "follow_link_set"}  %>
      </div>
    </div>

    <div class="notice_container">
      <% if @users.any? %>
        <%  @users.each do |user| %>
          <%=  link_to "/users/#{user.id}" do %>
          <div class="notice_container_item">
            <div class="notice_container_item2">
              <div class="notice_container_item_image">
                <div class="user_image">
                  <% if user.image? %>                                                              
                    <%= image_tag user.image.url(:thumb100), class: "image" %>
                  <% else %>
                    <img src="/assets/default.png" class="image" alt="ユーザーアイコン" >
                  <% end %>
                </div>
              </div>
              <div class="microposts_contents">
                <div class="microposts_info">
                  <div class="microposts_info_user">
                    <div class="micropost_user">
                      <%= user.name%>
                    </div>
                  </div>
                </div>
                <div class="micropost_content">
                  <%= user.introduction %>
                </div>
              </div>
          </div>
          </div>
        <% end %>
        <% end %>
        <%= will_paginate%>
      <% end %>
    </div>